### 1. Write the Python code to implement a single neuron.

In [1]:
import numpy as np

def single_neuron(X, weights, bias):
    return np.dot(X, weights) + bias

X = np.array([0.4, 0.5, 0.6])
weights = np.array([0.1, 0.2, 0.3])
bias = 0.4

output = single_neuron(X, weights, bias)

In [2]:
output

0.72


### 2. Write the Python code to implement ReLU.

In [3]:
def relu(x):
    return max(0, x)

# Example usage
print(relu(-5))  # Output will be 0
print(relu(5))   # Output will be 5

0
5


### 3. Write the Python code for a dense layer in terms of matrix multiplication.

In [4]:
def dense_layer(X, weights, bias):
    return np.dot(X, weights) + bias

X = np.array([[0.4, 0.5, 0.6],
              [0.1, 0.2, 0.3]])
weights = np.array([[0.1, 0.2],
                    [0.3, 0.4],
                    [0.5, 0.6]])
bias = np.array([0.1, 0.2])

output = dense_layer(X, weights, bias)

In [5]:
output

array([[0.59, 0.84],
       [0.32, 0.48]])

### 4. Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).

In [6]:
def dense_layer_plain_python(X, weights, bias):
    return [
        [
            sum(x * w + b for x, w, b in zip(X_row, W_col, bias))
            for W_col in zip(*weights)
        ]
        for X_row in X
    ]

X = [[0.4, 0.5, 0.6],
     [0.1, 0.2, 0.3]]
weights = [[0.1, 0.2],
           [0.3, 0.4],
           [0.5, 0.6]]
bias = [0.1, 0.2]

output = dense_layer_plain_python(X, weights, bias)

In [7]:
output

[[0.49, 0.5800000000000001], [0.37, 0.4]]

### 5. What is the “hidden size” of a layer?

The "hidden size" of a layer refers to the number of neurons or units in that layer.

---

### 6. What does the `t` method do in PyTorch?

The `t` method transposes a tensor in PyTorch. For 2D tensors, it swaps rows with columns.

---

### 7. Why is matrix multiplication written in plain Python very slow?

Matrix multiplication in plain Python is slow due to the nested loops and the fact that Python is an interpreted language, which makes operations like this inefficient compared to optimized libraries like NumPy.

---

### 8. In `matmul`, why is `ac==br`?

In matrix multiplication, the number of columns in the first matrix (`a`) must be equal to the number of rows in the second matrix (`b`) for the multiplication to be defined.

---

### 9. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?

You can use the `%%time` magic command at the start of the cell.

---

### 10. What is elementwise arithmetic?

Elementwise arithmetic performs operations on corresponding elements between two arrays.

---

### 11. Write the PyTorch code to test whether every element of `a` is greater than the corresponding element of `b`.

In [10]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([0, 1, 4])

result = torch.gt(a, b)  # or a > b

In [11]:
result

tensor([ True,  True, False])

### 12. What is a rank-0 tensor? How do you convert it to a plain Python data type?

A rank-0 tensor is a tensor containing a single scalar value. You can convert it to a plain Python data type using `.item()` in PyTorch.

In [12]:
x = torch.tensor(42)
plain_python_x = x.item()

In [13]:
plain_python_x

42

---

### 13. How does elementwise arithmetic help us speed up `matmul`?

Elementwise operations are more efficient because they can be parallelized easily, allowing for hardware-level optimizations.

---

### 14. What are the broadcasting rules?

Broadcasting allows tensors with different shapes to be combined. The smaller tensor is "broadcast" across the larger tensor so that they have compatible shapes.

1. Dimensions are compared element-wise starting from the trailing dimensions.
2. Two dimensions are compatible if they are equal or if one of them is 1.

---


### 15. What is `expand_as`? Show an example of how it can be used to match the results of broadcasting.

`expand_as` takes a tensor and expands it to the size of another tensor. This is useful for manual broadcasting.

In [15]:
import torch

a = torch.tensor([[1, 2]])
b = torch.tensor([[1, 2], [3, 4]])

expanded_a = a.expand_as(b)

# expanded_a will be [[1, 2], [1, 2]]

In [16]:
expanded_a

tensor([[1, 2],
        [1, 2]])